
export default {
  users: [
    {
      id: 1,
      userName: 'user1'
    },
    {
      id: 2,
      userName: 'user2'
    },
    {
      id: 3,
      userName: 'user3'
    },
    {
      id: 4,
      userName: 'user4'
    },
  ],
  eventsAll: [
    {id: 1, name: 'event1', location: 'Austin, Texas', date: 'date1', type: 'hiking', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user1', 'user3', 'user2', 'user4'], creator: 1},
    {id: 2, name: 'event2', location: 'SanAntonio, Texas', date: 'date2', type: 'biking', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user2', 'user3'], creator: 1},
    {id: 3, name: 'event3', location: 'Austin, Texas', date: 'date3', type: 'biking', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user3', 'user2'], creator: 4},
    {id: 4, name: 'event4', location: 'SanAntonio, Texas', date: 'date4', type: 'water', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user1', 'user2'], creator: 3},
    {id: 5, name: 'event5', location: 'Austin, Texas', date: 'date5', type: 'camping', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user2', 'user4'], creator: 1},
    {id: 6, name: 'event6', location: 'SanAntonio, Texas', date: 'date6', type: 'climbing', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user1', 'user3'], creator: 2},
    {id: 7, name: 'event7', location: 'Austin, Texas', date: 'date7', type: 'other', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user1', 'user3'], creator: 2},
    {id: 8, name: 'event8', location: 'SanAntonio, Texas', date: 'date8', type: 'water', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user3', 'user4'], creator: 1},
    {id: 9, name: 'event9', location: 'Austin, Texas', date: 'date3', type: 'biking', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user3', 'user2'], creator: 4},
    {id: 10, name: 'event10', location: 'SanAntonio, Texas', date: 'date3', type: 'biking', details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Amet facilisis magna etiam tempor orci. Sapien et ligula ullamcorper malesuada. Tincidunt tortor aliquam nulla facilisi. Ac auctor augue mauris augue neque gravida. Enim nec dui nunc mattis enim ut tellus elementum. Purus sit amet luctus venenatis lectus magna fringilla urna. Laoreet non curabitur gravida arcu ac. Dignissim enim sit amet venenatis urna cursus eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum.', users_attending: ['user3', 'user2'], creator: 4},
  ],
  discussionCards: [
    {id: 1, cardContent: 'card content 1', user_id: 1, event_id:3},
    {id: 2, cardContent: 'card content 2', user_id: 2, event_id:2},
    {id: 3, cardContent: 'card content 3', user_id: 3, event_id:2},
  ],
  discussionCardComments: [
    {id: 1, commentContent: 'comment content 1', user_id: 1, card_id: 1},
    {id: 2, commentContent: 'comment content 2', user_id: 2, card_id: 2},
    {id: 3, commentContent: 'comment content 3', user_id: 3, card_id: 3},
  ]
}